services:

  # Kafka (KRaft mode - no Zookeeper)
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # RocketMQ NameServer
  rocketmq-namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  # RocketMQ Broker
  rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-broker
    ports:
      - "10911:10911"
      - "10909:10909"
    depends_on:
      - rocketmq-namesrv
    environment:
      NAMESRV_ADDR: rocketmq-namesrv:9876
    command: sh mqbroker -n rocketmq-namesrv:9876 autoCreateTopicEnable=true
