spring:
  application:
    name: settlement
  data:
    redis:
      host: localhost
      port: 6370
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: settlement-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.sporty.settlement.domain"

# RocketMQ
rocketmq:
  name-server: localhost:9876
  producer:
    group: settlement-producer-group

topics:
  event:
    outcomes: event-outcomes
  bet:
    settlements: bet-settlements
    consumer-group: bet-settlements-consumer-group
