spring:
  application:
    name: settlement
  data:
    redis:
      host: localhost
      port: 6370
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: settlement-group-id

# RocketMQ
rocketmq:
  name-server: localhost:9876
  producer:
    group: settlement-producer-group
